Update test deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,7 +26,11 @@ jobs:
           extended: true
 
       - name: Build
-        run: hugo --gc
+        run: |
+          hugo --gc --minify
+          echo "Build completed"
+          ls -la
+          ls -la public || echo "Public directory not found!"
 
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v3
